services:
  swp_project_2024:
    container_name: swp_project_2024
    image: swp_project_2024
    build:
      context: .
      dockerfile: SWP_Project_2024/Dockerfile
  
  dbssed:
    container_name: db_SSED
    platform: linux/amd64
    image: amd64/postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sseddb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-tier

volumes:
  db_data: {}
  
networks:
  app-tier:
    driver: bridge