services:
  swp_project_2024:
    container_name: swp_project_2024
    image: swp_project_2024
    build:
      context: .
      dockerfile: SWP_Project_2024/Dockerfile
  
  db:
    container_name: db_SSED
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: